name: Trelnex.Mailboxes.Api Workflow

on:
  pull_request:
    paths:
      - .github/workflows/build.yml
      - .github/workflows/ci-cd-mailboxes-api.yml
      - Trelnex.Groups.Client/**
      - Trelnex.Mailboxes.Client/**
      - Trelnex.Mailboxes.Api/**
      - Trelnex.Users.Client/**
  push:
    branches: [ main ]
    paths:
      - .github/workflows/build.yml
      - .github/workflows/ci-cd-mailboxes-api.yml
      - Trelnex.Groups.Client/**
      - Trelnex.Mailboxes.Client/**
      - Trelnex.Mailboxes.Api/**
      - Trelnex.Users.Client/**
  workflow_dispatch:

jobs:

  # ---------------------------------------------------------------------
  # 1. Restore and Build
  # ---------------------------------------------------------------------
  build:
    uses: ./.github/workflows/build.yml

    with:
      dotnet_version: '9.0.x'
      project_name: 'Trelnex.Mailboxes.Api'

    secrets: inherit
