name: Trelnex.Users.Api Workflow

on:
  pull_request:
    paths:
      - .github/workflows/build.yml
      - .github/workflows/ci-cd-users-api.yml
      - Trelnex.Users.Client/**
      - Trelnex.Users.Api/**
  push:
    branches: [ main ]
    paths:
      - .github/workflows/build.yml
      - .github/workflows/ci-cd-users-api.yml
      - Trelnex.Users.Client/**
      - Trelnex.Users.Api/**
  workflow_dispatch:

jobs:

  # ---------------------------------------------------------------------
  # 1. Restore and Build
  # ---------------------------------------------------------------------
  build:
    uses: ./.github/workflows/build.yml

    with:
      project_name: 'Trelnex.Users.Api'

    secrets: inherit
